FROM python:3.9
WORKDIR /backend-dev
COPY . .
RUN pip install --no-cache-dir -r requirement.txt

RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

RUN python manage.py makemigrations core_app
RUN python manage.py migrate core_app

RUN python3 manage.py makemigrations
RUN python3 manage.py migrate

RUN rm -rf /static/
RUN python manage.py collectstatic

# Expose ports
EXPOSE 8001
# default command to execute    
#CMD ["python3", "manage.py", "runserver", "0.0.0.0:8001"] 
CMD exec gunicorn LMS.wsgi:application --bind 0.0.0.0:8001 --workers 3 
